version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: yt-shorts-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./downloads:/app/downloads
    mem_limit: 900m
    mem_reservation: 512m
    cpus: 1.0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"